In [ ]:
!pip install tensorflow_hub

In [ ]:
!pip install tensorflow_text

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 47.4 MB/s eta 0:00:00


In [ ]:
#import tensorflow hub and text
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
#to preprocess the text using allocated preprocessing model for basic BERT model(below)
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
#use basic encoder BERT model for encoding task
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [ ]:
#create hub layer
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [ ]:
#provide sample statements for preprocess
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test) #BERT modle act like a function pointer
text_preprocessed.keys() #dictionary

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [ ]:
text_preprocessed['input_mask']
#shape=(2, 128) 2 represents 2 sentences and 128 is like maximum lenth of the sentence
#the first sentence 'nice movie indeed' have three words.but when bert model works it add 2 special tokens in the beginning and the end
#so the sentence looks like 'CLS nice movie indeed SEP' now it have 5 words each word shown as 1 in binaries
#so the 1st sentence have 3+2 words then 5 1's 2nd sentence have 4+2 then 6 1's

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
text_preprocessed['input_word_ids']
#this sentence create by BERT models by adding extra 2 tokens 'CLS nice movie indeed SEP'
#wors ID for CLS and SEP are 101, 102 midlle 3 are uniqe ID's for remaining middle words, 4 middle ID's for 2nd sentence

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
text_preprocessed['input_type_ids']
#the prerocessing stage is done.

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
#then we create another layer for encoding part
bert_model = hub.KerasLayer(encoder_url)

In [ ]:
bert_results = bert_model(text_preprocessed) #BERT modle act like a function pointer

In [ ]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'default', 'encoder_outputs'])

In [ ]:
bert_results['pooled_output']
#pooled output is the embedding for entire sentences
#2 sentences and embedding vector size is 768

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917741 , -0.21411921,  0.49769515, ...,  0.24465193,
        -0.47334474,  0.8175871 ],
       [-0.91712314, -0.47935188, -0.78656995, ..., -0.61751765,
        -0.7102687 ,  0.921843  ]], dtype=float32)>

In [ ]:
bert_results['sequence_output']
#this is individual word embedding vectors
#2 is for 2 sentences
#for each individual senteces we have some paddings that is what 128 represent. 128 is like maximum lenth of the sentence
#'nice movie indeed 0 0 0 0 0 0' <---- 128
#and for each word there is a 768 size embedding vector
#this is contextualized embedding that's why sentences have paddings like above
#these words have some context

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567815,  0.14476833, ..., -0.09677089,
          0.08722138,  0.07711098],
        [ 0.17839392, -0.19006105,  0.50349474, ..., -0.05869799,
          0.32717094, -0.15578488],
        [ 0.18701468, -0.43388787, -0.48875138, ..., -0.15502772,
          0.00145124, -0.24470966],
        ...,
        [ 0.12083106,  0.12884258,  0.46453524, ...,  0.07375515,
          0.17441994,  0.16522008],
        [ 0.07967864, -0.01190711,  0.50225407, ...,  0.13777758,
          0.21002217,  0.00624588],
        [-0.07212694, -0.2830348 ,  0.59033334, ...,  0.47551954,
          0.16668473, -0.08920345]],

       [[-0.07900596,  0.36335123, -0.2110157 , ..., -0.17183766,
          0.1629974 ,  0.6724269 ],
        [ 0.27883503,  0.43716323, -0.35764694, ..., -0.0446365 ,
          0.3831516 ,  0.5887988 ],
        [ 1.203767  ,  1.0727018 ,  0.4840876 , ...,  0.24920997,
          0.40730938,  0.404818  ],
        ...,

In [ ]:
len(bert_results['encoder_outputs'])
#12 means we are using small BERT base model and it contains 12 encoder layers. each layer has 768 size embedding vector
#so these encoder outputs is nothing but the output of each individual act encoder. So we have 12 that's why 12 is the size

12

In [22]:
bert_results['encoder_outputs'][0]
#the 1st encode layer

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12901433,  0.00644742, -0.03614973, ...,  0.04999627,
          0.06149201, -0.02657528],
        [ 1.1753385 ,  1.2140789 ,  1.1569982 , ...,  0.11634358,
         -0.3585536 , -0.4049018 ],
        [ 0.03859036,  0.5386998 , -0.21089786, ...,  0.21858224,
          0.7260168 , -1.1158603 ],
        ...,
        [-0.0758702 , -0.25421908,  0.7075512 , ...,  0.50542   ,
         -0.1887868 ,  0.15028337],
        [-0.16066599, -0.28089687,  0.5759707 , ...,  0.52758545,
         -0.11141391,  0.0288756 ],
        [-0.04428162, -0.20279588,  0.59093565, ...,  0.8133835 ,
         -0.39075804, -0.02601745]],

       [[ 0.1890359 ,  0.02752538, -0.06513739, ..., -0.00620209,
          0.15053897,  0.03165445],
        [ 0.5916149 ,  0.75891405, -0.07240669, ...,  0.6190399 ,
          0.82928926,  0.16161972],
        [ 1.4460827 ,  0.4460263 ,  0.40990257, ...,  0.48255897,
          0.6269115 ,  0.13463408],
        ...,

In [23]:
bert_results['encoder_outputs'][-1]
#for the last encode layer

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567815,  0.14476833, ..., -0.09677089,
          0.08722138,  0.07711098],
        [ 0.17839392, -0.19006105,  0.50349474, ..., -0.05869799,
          0.32717094, -0.15578488],
        [ 0.18701468, -0.43388787, -0.48875138, ..., -0.15502772,
          0.00145124, -0.24470966],
        ...,
        [ 0.12083106,  0.12884258,  0.46453524, ...,  0.07375515,
          0.17441994,  0.16522008],
        [ 0.07967864, -0.01190711,  0.50225407, ...,  0.13777758,
          0.21002217,  0.00624588],
        [-0.07212694, -0.2830348 ,  0.59033334, ...,  0.47551954,
          0.16668473, -0.08920345]],

       [[-0.07900596,  0.36335123, -0.2110157 , ..., -0.17183766,
          0.1629974 ,  0.6724269 ],
        [ 0.27883503,  0.43716323, -0.35764694, ..., -0.0446365 ,
          0.3831516 ,  0.5887988 ],
        [ 1.203767  ,  1.0727018 ,  0.4840876 , ...,  0.24920997,
          0.40730938,  0.404818  ],
        ...,

In [24]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']
#encoder output is the encoder output of all 12 layers and the last one is same as the sequence output

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

In [25]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901433,  0.00644742, -0.03614973, ...,  0.04999627,
           0.06149201, -0.02657528],
         [ 1.1753385 ,  1.2140789 ,  1.1569982 , ...,  0.11634358,
          -0.3585536 , -0.4049018 ],
         [ 0.03859036,  0.5386998 , -0.21089786, ...,  0.21858224,
           0.7260168 , -1.1158603 ],
         ...,
         [-0.0758702 , -0.25421908,  0.7075512 , ...,  0.50542   ,
          -0.1887868 ,  0.15028337],
         [-0.16066599, -0.28089687,  0.5759707 , ...,  0.52758545,
          -0.11141391,  0.0288756 ],
         [-0.04428162, -0.20279588,  0.59093565, ...,  0.8133835 ,
          -0.39075804, -0.02601745]],
 
        [[ 0.1890359 ,  0.02752538, -0.06513739, ..., -0.00620209,
           0.15053897,  0.03165445],
         [ 0.5916149 ,  0.75891405, -0.07240669, ...,  0.6190399 ,
           0.82928926,  0.16161972],
         [ 1.4460827 ,  0.4460263 ,  0.40990257, ...,  0.48255897,
           0.6269115 ,  0.13